import type { Metadata } from "next";
import Navbar from "@/components/ui/custom/Navbar";
import Footer from "@/components/ui/custom/Footer";
import "./globals.css";

export const metadata: Metadata = {
  title: "Lucky Jackpot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="cs-cz">
      <body className=" bg-zinc-800 text-[#F9F9F9]">
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
